### ISSUE TITLE
PDF files with CRLF

### ISSUE THREAD

**Issue by AlanUS** [JMRI/website#109]
I have restarted from a brand new fork of the JMRI website. After cloning it in my local repository, through NetBeans, I opened the local repo through GitHub desktop which showed me one file change, despite a fresh installation .
This is \community\clinics\NMRA2011\JMRI-Operations-X2011.pdf
This file is a PDF generated from a PowerPoint (or alike) presentation. I opened it with NotePad++ with Line Ends showed. It contains CRLF.

I found this post which could give some hint about what is happening:
http://stackoverflow.com/questions/5009096/files-showing-as-modified-directly-after-git-clone

Actually my local git is set with `autocrlf = true` and currently PDF files are not specified in the newest .gitattributes. So it might be that Git's intention is to force this file to be saved with LF.

Anyway, I discarded the "change" as I don't want to make any change to this file.

It could however be good to add PDF files to .gitattributes, but I don't know with what marker. Would `-diff` be sufficient, as we don't really want to diff PDF files, but they are not binary either.

**Comment by mattharris** [comment]
In the context of change management, I would suggest that we treat pdf files as binary - there isn't really any useful diff that we can perform on them as a text file.

HTML and java files are, at their core, text files.

Now, whilst pdf files typically contain text, it's not usually in a suitable form for diffing.

**Comment by bobjacobsen** [comment]
PDF files are now includes as binary.  Thanks!
