### ISSUE TITLE
Use PRs to update release note?

### ISSUE THREAD

**Issue by bobjacobsen** [JMRI/website#129]
I merge a fair number of PRs in the JMRI/JMRI repository.  Some of those should get entries in the next release note.

I'd like to make it easy-as-possible for people to make entries in the release note when they merge a PR.

Do we (maintainers who are merging PRs in the other repository) really need to use the full PR mechanism for those? It seems quite heavyweight, as opposed to doing a commit & direct push either from my local machine, or via the web editor (which I'm really coming to like). 

Would be interested in what the consensus is about the value of doing the PR.

**Comment by rhwood** [comment]
I like the idea of automatically generating release notes from PRs and Issues by iterating over the titles of PRs and Issues associated with the milestone/release in question.

**Comment by bobjacobsen** [comment]
> I like the idea of automatically generating release notes from PRs and Issues

Do you mean just doing that once manually as part of the release step? Or just using the existing titles, perhaps with formatting.

We do link that in the release note (see the [4.3.2](https://github.com/JMRI/JMRI/issues?utf8=✓&q=is%3Aclosed&q=milestone%3A4.3.2+) example), but I think it would take a lot before that was really usable without a translation step.  

Of course, maybe nobody actually reads the release notes.

**Comment by dheap** [comment]
I don't think PR comments will ever be sufficient/relevant/comprehensible as release notes for average JMRI users. We need concise plain-language release notes of the end result as it affects the user, not all the code steps on the way, meaningful only to us.

Linking to them as we do now is fine for the curious (if there are any), but I see no way to satisfactorily automate the translation without alienating our users.
> We do link that in the release note (see the 4.3.2 example), but I think it would take a lot before that was really usable without a translation step.
>

**Comment by dheap** [comment]
I thought the discussion was about eliminating the PR process for JMRI/website so developers commit and push directly to JMRI/website rather than to their own forks and raising a PR.

@bobjacobsen did I read your first comment correctly?

**Comment by dheap** [comment]
To expand my earlier comment with an example, if a developer adds or modifies constructors in say AbstractProgrammer.java or adds another protected or public method, that information is quite likely of importance to fellow developers, either immediately or in future when examining file history.

But that commit means nothing to the average Joe JMRI user, even though a further consequent-development may result in better prioritising programming mode order for system xyz, which is relevant to Joe.

PR comments are useful for developers, and for checking if we have covered all relevant bases in release notes, but need intelligent filtering and translation by a human developer.

We all need to keep the release notes up-to-date as we go (says he who is often guilty of last minute updates), so anything that makes the process quicker and less burdensome could be helpful.

**Comment by bobjacobsen** [comment]
> @dheap:  did I read your first comment correctly?

Yes. _Just_ for updates to the release note e.g. from merging a PR, can we get a consensus that direct commits are OK?

**Comment by bobjacobsen** [comment]
On the larger question of release note structure and source (which maybe should be a separate Issue), I agree that improvements would be good.  If there was a way to encourage the people creating the PR to also create useful release note comments, that would be good.  For the old SF patches, I tended to take the comments from the tracker entry and put them in the release note. Except they were often pretty terse...

It would be best if there was a way to have the PR author include the release note update themselves. Moving the release notes to the help/ tree would be a step.  But given that PRs can sit around for a bit, I don't see how to avoid something like this causing lots of merge conflicts.

**Comment by bobjacobsen** [comment]
Just to see how it works, I just pushed a single commit without a PR: 9f08c8ce03baa7

It shows up on the [commits list page](https://github.com/JMRI/website/commits/master), and shows (transiently) at the top of my view of the repository:

![jmri_website__the_jmri_org_website](https://cloud.githubusercontent.com/assets/2774117/12434368/2531eff8-bebb-11e5-83dc-0ec814a28630.png)

But of course there's no PR in the list for this.

Comments welcome as to whether this is an OK approach for PRs _only_.

**Comment by dheap** [comment]
@bobjacobsen: So the idea is that if we adopt it,  for release note updates only we do a:
    git push https://user@github.com/JMRI/website.git
rather than a:
    git push
(which defaults to https://user@github.com/user/website.git if the config file is set up correctly)
Is that syntax correct/best?

> Yes. Just for updates to the release note e.g. from merging a PR, can we get a consensus that direct commits are OK?

**Comment by bobjacobsen** [comment]
I work from the command line, so I've done a 
````
git remote add github https://github.com/JMRI/website.git
````
to define a "github" remote.  (You can pick another name; note that user info isn't required, it Knows Who You Are)  Then to push directly I do
````
git push github
````
which I find much easier to remember than the full syntax.

**Comment by rhwood** [comment]
Use whatever workflow is best for you.

I'm all for this change, but will only use it myself unless I am editing the release notes directly in the GitHub website. My local git clone workflow is PR oriented, and I have no real value in changing that for this use case.

**Comment by mattharris** [comment]
I don't see any issues in using a direct commit workflow in this case.

Larger changes should still go over a PR-based workflow.

But, as @rhwood mentions, we can still use a PR-based workflow for all changes - it's up to the individual (those with write access to the repo - members of `maintainers` team) to use the workflow that suits them best.

**Comment by dheap** [comment]
There's some historical reason for the username in URLs in my Git config file. I think it may have happened when I used NetBeans to checkout.

I too do all my commits, pushes and pulls from the command line, but the bash history tools (ctrl-r in particular) make complexity irrelevant.

But defining a new remote name is a useful tip, thanks.

> to define a "github" remote. (You can pick another name; note that user info isn't required, it Knows Who You Are) Then to push directly I do
