### ISSUE TITLE
Lighter Sf logo on JMRI help

### ISSUE THREAD

**Issue by silverailscolo** [JMRI/website#251]
Could one of our SourceForge administrators check the following page to see if an alternative Sf badge is provided to use in the jmri.org footer: https://sourceforge.net/p/forge/documentation/SourceForge%20Logo/
I find the new default looks relatively dark in contrast to our page layout style.

**Comment by rhwood** [comment]
There are alternative badges:
- [![Download JMRI Model Railroad Interface](https://sourceforge.net/sflogo.php?type=11&group_id=26788)](https://sourceforge.net/p/jmri/)
  `<a href="https://sourceforge.net/p/jmri/"><img alt="Download JMRI Model Railroad Interface" src="https://sourceforge.net/sflogo.php?type=11&group_id=26788" ></a>`
- [![Download JMRI Model Railroad Interface](https://sourceforge.net/sflogo.php?type=13&group_id=26788)](https://sourceforge.net/p/jmri/)
  `<a href="https://sourceforge.net/p/jmri/"><img alt="Download JMRI Model Railroad Interface" src="https://sourceforge.net/sflogo.php?type=13&group_id=26788" ></a>`
- [![Download JMRI Model Railroad Interface](https://sourceforge.net/sflogo.php?type=14&group_id=26788)](https://sourceforge.net/p/jmri/)
  `<a href="https://sourceforge.net/p/jmri/"><img alt="Download JMRI Model Railroad Interface" src="https://sourceforge.net/sflogo.php?type=14&group_id=26788" ></a>`
- [![Download JMRI Model Railroad Interface](https://sourceforge.net/sflogo.php?type=16&group_id=26788)](https://sourceforge.net/p/jmri/)
  `<a href="https://sourceforge.net/p/jmri/"><img alt="Download JMRI Model Railroad Interface" src="https://sourceforge.net/sflogo.php?type=16&group_id=26788" ></a>`

Note the difference in these badges is the "type" parameter. There is also a type "17" badge, but its size must be specified, and it cannot be used in markdown syntax.

**Comment by silverailscolo** [comment]
Thanks, I would suggest either of the badges with a white background color, especially since on the dark gray style the last ``E`` is too close to the right hand edge to be applied over a white page.

**Comment by bobjacobsen** [comment]
The type 16 logo is 150x40. Type 13 is 120x30.

On most of our existing pages, we've hard-coded 120x30, with a few 88x31 and a couple other sizes; not sure why.  Most of the references are pretty straight-forward, but there are a couple with extra attributes.  There are 86 in the 'website' repo, 30 in the 'JMRI' repo; the JMRI ones are mostly XSLT transforms that label the output, but its also labeling Javadoc output, etc.

I recommend (which means I'm willing to eventually do) that we create a new "Icon" include file, like the existing Header, Footer, etc, put that in place of the references in the .shtml files, and start with Type 13 as it's content.  There will be a few places that might not look right, but we can fix them as we find them.  For the references in XSLT transforms, we skip the attributes (height, width, etc) and just use the raw URL for type 13.

Does that work for people?

**Comment by rhwood** [comment]
I would actually just remove the SourceForge logo unless we are going to add the GitHub logo. We are, after all, having this discussion on GitHub, not SourceForge.

**Comment by bobjacobsen** [comment]
The web pages are served from SF servers. I haven’t checked recently, but SF used to ask that on of those badges appear on pages they serve. 

We could add a GitHub badge in addition.

**Comment by bobjacobsen** [comment]
I think this has been covered by #252 and JMRI/JMRI#4742.  Jenkins will update the web server shortly.

**Comment by silverailscolo** [comment]
Thanks, looking good
