### ISSUE TITLE
Add SoundTraxx Econami UK to release note 4.11.2

### ISSUE THREAD

**Issue by AlanUS** [JMRI/website#256]
Can this be added to the release note of version 4.11.2? 
https://github.com/JMRI/JMRI/pull/4710
Thanks

**Comment by bobjacobsen** [comment]
Done, sorry for delay.

**Comment by AlanUS** [comment]
@bobjacobsen 
Thanks. I did not prepare a PR for this, as I think that the convention is to update the website pages directly in GitHub, which limits this to the few with write access.

**Comment by bobjacobsen** [comment]
@AlanUS  Not a problem either way.  If it's easier for you to prepare a PR, that's fine, it'll get merged pretty quickly.  But this is fine too, particularly if the original item has enough detail that it can just be copied over.

**Comment by pabender** [comment]
Sent from my iPad

> On Feb 24, 2018, at 12:29 PM, Alain LM <notifications@github.com> wrote:
> 
> @bobjacobsen
> Thanks. I did not prepare a PR for this, as I think that the convention is to update the website pages directly in GitHub, which limits this to the few with write access.
> 

No, the web pages, like the source are, updated with PRs.  The website itself is in the https://github.com/JMRI/website repository.

**Comment by AlanUS** [comment]
@bobjacobsen @pabender 
OK no problem to work with PR.
I'm not modifying a lot the web site / release notes, but I remember to have been advised just after the migration to GitHub not to use PRs for the website.
I definitely prefer to work with PRs. Don't want to give any of you guys extra work when I can do it myself.
