### ISSUE TITLE
Tagadab renamed to Simply Cloud

### ISSUE THREAD

**Issue by silverailscolo** [JMRI/website#317]
23 May I noticed that at the bottom of the JMRI help pages the Tagadab badge is blank (alt text).
Clicking on the icon/hyperlink brought me to their page, where an announcement said they have renamed their service to SimplyCloud.
This seems to ask for an update of this badge in the /footer include file and several other places. Can't quickly locate an official badge provide by the operator. Fixed in PR #316.
Hosting JMRI coordinator @SteveRawlinson please check.

**Comment by SteveRawlinson** [comment]
Yes, Tagadab has been acquired and rebranded. You are very welcome to use the new logo, or indeed remove the logo, whatever's good for you,
