### ISSUE TITLE
PanelPro page fails

### ISSUE THREAD

**Issue by sidlo64** [JMRI/website#318]
From top page http://jmri.org/ link to **PanelPro** fails to page 
http://jmri.org/var/www/html/help/en/html/apps/PanelPro/index.shtml
with error **404 Not found**
the right link is http://jmri.org/help/en/html/apps/PanelPro/index.shtml

**Comment by silverailscolo** [comment]
Thanks. Fixed as part of PR #316

**Comment by sidlo64** [comment]
Fixed by PR #316
