### ISSUE TITLE
DigiTrains Android App for running trains from JMRI Version is obsolete.

### ISSUE THREAD

**Issue by RailConMan** [JMRI/website#322]
The Digitrains Android App is not being updated anymore for about 2-3 years. Now a new version is available called Digitrains Pro. Which is more used friendly and has more options for connecting to JMRI, Z21 and Digikeijs plus more. User interface is better.

There is a new Goggle Store Store available for this. 
https://play.google.com/store/apps/details?id=digitrainspro.digitrainspro.hu&hl=en_US

"Using DigiTrains, Pro you can control your model railroad layout from your phone, tablet, or computer via WIFI.
From the locomotive library you can easily and quickly select the locomotive you want to control.
You can reach the speed, direction and all the features of the locomotive with a single touch while you are free to move around your layout.
Finally, you do not have to remember the addresses, you can play very simply, even with multiple trains.
You can add additional data and picture to trains, sort them into groups, and filter in locomotive library for any data or group.
You can add all your accessories (turnouts, lights, etc.) and switch them from the app.
You can also control your layout as a dispatcher in Dispatcher Game. Use station speaker announcements with signals.
The following digital command centers are compatible with the app: Roco Z21, JMRI, Digikeijs DR5000, Digitools DigiWifi, DigiTools DigiProgrammer, DTPro Club Server and more to come."

Dennis Cherry

**Comment by bobjacobsen** [comment]
Thanks!  Update in #323
