### ISSUE TITLE
Signaling System pages generated incorrectly

### ISSUE THREAD

**Issue by devel-bobm** [JMRI/website#329]
Signal System "appearance files" have not yet been migrated to "https:" (see #324).

My browsing of jmri.org, looking at signaling system definitons, shows a consistent effect that mast-specific web pages all display along the lines of:

"Slow Clear
Error: This appearance does not appear in the aspect table. Check spelling and upper/lower case."

This seems to be caused by a reference to `http://jmri.org/xml/schema/appearancetable.xsd` which appears to be hard-coded in the "appearance" files for every signal system definition.  Each reference requires updating.

Presumably this problem could also affect the ability of users of older JMRI installs to properly "view" the appearance files on their computer using a web browser.  In this case, a web site "redirect" would seem to be in order.

**Comment by mattharris** [comment]
@devel-bobm Thanks for the heads-up. I'll double-check the Jenkins task that, usually, should deal with the regeneration of these files.

Plus, I'll add a configuration to the web site to allow these xsd's to be served via http as well as https.

**Comment by mattharris** [comment]
Further investigation shows that root cause seems to be the xsl transform used to format these pages.

The referenced schema location did not appear to be a problem as upgrade of that request to https is being handled correctly by the browser.

**Comment by mattharris** [comment]
This now looks to be resolved - @devel-bobm can you confirm?

**Comment by devel-bobm** [comment]
I can confirm that the JMRI web site now properly displays the mast aspect information at web pages like [https://www.jmri.org/xml/signals/SLSF-1973/appearance-SL-3-triangle.xml](url).  The fix has changed the `Error: This appearance does not appear in the ...` message with the appropriate text from the signal mast appearance file.

Thanks Matt!
