### ISSUE TITLE
MacOS and Java

### ISSUE THREAD

**Issue by Tenderschieber** [JMRI/website#333]
When starting Decoder Pro 4.16+R6f9aced on MacOS it uses

JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"

But this isn't supported for years so you face some trouble if you have a newer installation.

The proper line is

JAVA_HOME=$( /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java_home )

which also causes trouble since the start script uses these lines:

function heap_size() {
    # get Java heap size                                                                                                                                        
    heap=$( "${JAVACMD}" -XX:+PrintFlagsFinal -version 2>/dev/null | grep MaxHeapSize | awk '{print $4}' )
    heap=$( expr ${heap} / 1048576 ) # bytes to MB                                                                                                              

But this causes an error because of a bug in Bash or somewhere else which delivers **two** lines. This error appears only in non-interactive mode but not interactively.

So the solution (or workaround) is:

function heap_size() {
    # get Java heap size                                                                                                                                        
    heap=$( "${JAVACMD}" -XX:+PrintFlagsFinal -version 2>/dev/null | grep MaxHeapSize | awk '{print $4}' )
    heap=$( echo ${heap} | awk '{print $1}' )
    heap=$( expr ${heap} / 1048576 ) # bytes to MB                                                                                                              

It removes the unnecessary value and the shell script starts without any error.

**Comment by bobjacobsen** [comment]
@Tenderschieber Thank you!  I've moved this to JMRI/JMRI#7541 as it's a development item that's more likely to get attention there.  (This repository contains just the web site, not the scripts et al)  If you can add a comment there, I'll be able to link you to that Issue.

**Comment by bobjacobsen** [comment]
This should be fixed in JMRI 4.17.5, now released.
