### ISSUE TITLE
Web page shows up without header: https://www.jmri.org/community/clinics/

### ISSUE THREAD

**Issue by jerryg2003** [JMRI/website#359]
...and I can't figure out why.  Using Chrome on my PC, there is just blank white space.  
HTML up to and through the "include" for /header.shtml looks the same as other pages where header shows up just fine.

Any thoughts @bobjacobsen @icklesteve ?

Thanks, Jerry

**Comment by bobjacobsen** [comment]
I think the cause is the community/clinics/index.html file has a .html suffix, not .shtml

**Comment by jerryg2003** [comment]
I’ve put changing all .html to .shtml on my list.  Thanks.

**Comment by silverailscolo** [comment]
Fixed since, closing issue
