### ISSUE TITLE
Placement of div=mBody

### ISSUE THREAD

**Issue by jerryg2003** [JMRI/website#360]
@bobjacobsen @icklesteve I found that all of the files in the /install directory reference the sidebar in the /download directory (I’ll deal with that later...).  The issue is that sidebar currently has a div=mBody statement in the sidebar rather than in the main file like everywhere else a sidebar is used (throughout the JMRI repository). The corresponding /div statement is in the main file, which is “clearly confusing.”

Btw, the template file for help files correctly has the div and /div in the same file.

Can I enlist your help in somehow changing the files in /install or do I have to do a manual change to each file (about 50)?

Thanks, Jerry

**Comment by bobjacobsen** [comment]
I can do a bulk replace for this, but I'm not sure what exactly I'm supposed to do.  Is it removing a div element?  Which one?

**Comment by jerryg2003** [comment]
@bobjacobsen actually, one line needs to be added in 50 files so one line can be removed from a single file.  Seems counterintuitive that this would be the right thing to do (add 49 lines of code to the repository) but actually will make HTML more understandable (puts div and /div in the same file) and consistent with what is done throughout the JMRI repository.  What I would really like to do is:

1. Add ‘<div id=“mBody”>’ above the “include virtual=/download/Sidebar.shtml” in all files in the /install directory. (About 50 files).
2. In those same files, change that include to reference virtual=“Sidebar.shtml” (i.e. a new one we will create in the /install directory).
3. Copy /download/Sidebar.shtml to create /install/Sidebar.shtml.
4. Remove the div id=mBody statement from /install/Sidebar.shtml.

Hope this makes sense to you as it does to me!  If not, well, there are plenty of other things vying for your time...

Thanks, Jerry

**Comment by jerryg2003** [comment]
Whoops:  the missing statement in the above comment is:
div id=[double quote]mBody[double quote]

**Comment by bobjacobsen** [comment]
On the first part, restating to ensure I understand, I'm to change
```
<!--#include virtual="/download/Sidebar.shtml" -->
```
to 
```
<div id=“mBody”>
<!--#include virtual="Sidebar.shtml" -->
```
in all the install/*.shtml files. This doesn't include descending into and changing contents of /install subdirectories

That, plus the changes to /install/Sidebar.shtml, seem to be working OK on my local copy.

Changes in PR #361
