### ISSUE TITLE
Adding “date last modified” to web page footers

### ISSUE THREAD

**Issue by jerryg2003** [JMRI/website#369]
@mattharris @silverailscolo @bobjacobsen  (the three people who have edited Footer.shtml in the past, but of course anyone can comment):

As I continue my review of help/web pages, I’m finding many (too many) that are out of date with the software - some by a little (e.g. the Preferences Pane page is missing two items) and some by more (seven supported hardware components were missing from the hardware list on the sidebar and the Hardware page).  As a user frequenting these pages to learn about another part of JMRI, I find this frustrating and I’m sure others do too.  So...

What about putting a line in the footer which indicates when the page was last updated?  At least the user will get this when looking at the web to see why the help page might not correspond to what he or she is seeing in the JMRI program. 

I’ve come across several examples of how to do this, and could easily just add this line to Footer.shtml that is used by almost all help/web pages:

(Greater than and less than omitted)
script language="Javascript"
document.write("This page was last modified on: " + document.lastModified +"");
/script

What do you think?
Jerry

**Comment by bobjacobsen** [comment]
I don't think that will work as you expect.  The dynamic last-modified date in a web browser is typically when the page was served.

It's possible to get Git to substitute a date when a file is committed, but it's a complicated thing.  See the bottom of the "Keyword Expansion" section on https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

**Comment by bobjacobsen** [comment]
I haven't found a way to do this dynamically. 

We could write a script to go through and update some specific text in each file with the git log date, but that seems quite heavy-weight. 

Or establish a convention that people manually update something on the bottom of the page?

Maybe the simplest thing is to have people check the date by looking in GitHub. That's definitive. To do it, just prepend `https://github.com/JMRI/website/blob/master/` to the file path, i.e. `https://github.com/JMRI/website/blob/master/community/connections/CATS.shtml`. That makes the entire history accessible. (We could even add that link automatically to the bottom of pages)

**Comment by jerryg2003** [comment]
Resolved for now with PR #375
