### ISSUE TITLE
Cannot operate withrottle, button returns to off.

### ISSUE THREAD

**Issue by 1ngwpower** [JMRI/website#381]
Have DCS 51, PR3, connected with Loconet. Can open from DecoderPro and PanelPro. Will load my roster and I turn on the power button in a few seconds the power button goes to off.
![Loconet   withrottle](https://user-images.githubusercontent.com/55358632/94606817-dd18e400-024f-11eb-9897-680a0182626e.jpg)

**Comment by danielb987** [comment]
@1ngwpower 
Thanks for your issue. Please post this issue in the [JMRI/JMRI](https://github.com/JMRI/JMRI/issues) projekt since most of the developers looks there instead.

**Comment by 1ngwpower** [comment]
> @1ngwpower
> Thanks for your issue. Please post this issue in the [JMRI/JMRI](https://github.com/JMRI/JMRI/issues) projekt since most of the developers looks there instead.

Danielb987 how do I get to JMRI/JMRI projekt as I do not see a way to post at JMRI/JMRI projekt.

**Comment by danielb987** [comment]
Follow this link:
https://github.com/JMRI/JMRI/issues

**Comment by silverailscolo** [comment]
Moved to JMRI/JMRI issue #9051. Closing this here.
