### ISSUE TITLE
JMRI.org responsive

### ISSUE THREAD

**Issue by silverailscolo** [JMRI/website#382]
I'm working on a PR to bring the website up to date for "responsive", eg. mobile browsing. Will impact some graphics too (fewer boxes and borders, color scheme) but mostly css3, html5 and some JavaScript to support navigation on different viewports.
@mattharris it seems best to create a small demo folder to test and review, without messing with the current website till a new one's working.
Current draft on mobile:
![ios_prev2](https://user-images.githubusercontent.com/14811327/100268597-90067500-2f55-11eb-90e2-212165b677ca.png)  ![resp-small-menu](https://user-images.githubusercontent.com/14811327/101940635-12926400-3be7-11eb-8bf5-8a1d19e7bba0.png)  ![resp-small-side](https://user-images.githubusercontent.com/14811327/101940650-17efae80-3be7-11eb-8eee-4252fc16cb45.png)

Same page viewed on a bigger screen:
![responsive-large](https://user-images.githubusercontent.com/14811327/101939774-bf6be180-3be5-11eb-9c02-cd4f60d442ee.png)

**Comment by danielb987** [comment]
Thanks. It would be great if you could write some documentation on it as well. If I write a new web page for JMRI, what do I need to think of to make resposive work?

**Comment by silverailscolo** [comment]
I will be glad to add a page on that. Now that you mention it, it might even be good to start on that soon as it could also be a good place to showcase and test some of those items.
Fortunately the base of the current web pages don't require a lot of overhaul.
More ideas for colors by [DesignHack](https://designshack.net/articles/trends/best-website-color-schemes/)

**Comment by silverailscolo** [comment]
See PR #388

**Comment by silverailscolo** [comment]
Updates have been implemented and is now live. Further fine tuning ongoing, closing this issue.
