### ISSUE TITLE
"windows new" page has wrong sidebar?

### ISSUE THREAD

**Issue by bobjacobsen** [JMRI/website#383]
https://www.jmri.org/install/WindowsNew.shtml  seems to be referencing the wrong sidebar, because it's not showing the same "release notes" list of releases as e.g. https://www.jmri.org/download/index.shtml

**Comment by jerryg2003** [comment]
There are separate sidebar.shtml in the "install" and "download" sub-directories with hardcoded list of "release notes" (perhaps other places as well?).  Solution would be to create a "part" called SidebarReleaseNotes.shtml and use an include to that.  The current "parts" are stored n the JMRI/JMRI repository under help/en/parts so I don't know if that would cause a problem with files stored in JMRI/Web repository.  [Kind of links to my longer term idea of merging these two repositories, except for large PDF files currently stored in JMRI/Web.]  What do you think?

**Comment by jerryg2003** [comment]
On further investigation, it look like there ar only 2 Sidebar.shtml with hard-coded release note numbers.  I updated the one in “install” with PR #407 which should solve the problem.  When new releases are created, someone will have to update the Sidebar.shtml in the “install” directory as well as the “download” directory for now.
