### ISSUE TITLE
Raspberry Pi instructions need a rework.

### ISSUE THREAD

**Issue by jszinger** [JMRI/website#392]
The Page “Installing JMRI on Raspbian” `https://www.jmri.org/install/Raspbian.shtml` has several issues:

* The hardware listed is the 2B, but JMRI also runs on later versions.
* The instructions should focus on installing the current JMRI on the current Raspberry PI OS.  Exceptions for older JMRI and OS installations should be removed moved to a separated section.
* The cross references between the steps is messed up.  For example, Step 5 refers to step 7, but there is no step 7.
* I think it is no longer necessary to disable IPv6—JMRI 4.21.4 on RPiOS 10 works just fine with it, including WiThrottle.
* There should be a warning the JMRI is not supported on aarch64 since the necessary JNI support is missing. (Same basic issue as `https://github.com/JMRI/JMRI/issues/9197` but for Linux instead of Mac.)

**Comment by dsand47** [comment]
The attached pdf is a proposed Raspberry Pi install.  It is a new file.  The old one will remain for historical reasons and linked from the new one.  The formatting is not the best since the print to PDF CSS does not handle everything that the browser displays.

[Installing JMRI on Raspberry Pi OS.pdf](https://github.com/JMRI/website/files/11468659/Installing.JMRI.on.Raspberry.Pi.OS.pdf)

**Comment by danielb987** [comment]
> Autostart
> To automatically start the GUI version of PanelPro
> or DecoderPro during startup, add a symbolic link
> to the desktop icon.
> 
> cd ~/.config mkdir autostart (might not exist)
> cd autostart ln -s ~/Desktop/PanelPro.desktop
> PanelPro.desktop

I don't know if it's a misstake or if the PDF is wrong, but there seems 
to be several commands on a single line here.


> Faceless setup using PanelPro
> ...
> 5. Starting JmriFaceless
>   * Connect using ssh and enter ~/JMRI/JmriFaceless
>   * Start using a ssh remote command:
>     ssh <user>@<ip address> /home/<user>/JMRI/JmriFaceless &
>   * Add a line to the rc.local file before the exit 0:
>     sudo -u <user>/home/<user>/JMRI/JmriFaceless &

I have difficult to understand these instructions. Does "enter 
~/JMRI/JmriFaceless" mean that I should go to that folder?

> Start using a ssh remote command: ssh <user>@<ip address>

Should I do this after I have connected with ssh to the RPi? The first 
point says I should connect with ssh. The second point says I should 
connect with ssh.

> Add a line to the rc.local file before ...

Where is the rc.local file located? /etc/rc.local?


> LogixNG has a Shutdown action. This example uses
> a sensor that can be set from a browser connected
> to the JMRI Web Server.
> 
> LogixNG: Shutdown ConditionalNG: Shutdown ! A If
> Then Else. Execute on change ? If Sensor Shutdown
> is Active ! Then Shutdown JMRI/computer: Shut down
> the computer ! Else

This LogixNG has no line breaks. A misstake or a problem with the PDF?

**Comment by dsand47** [comment]
The print CSS has issues with some content.  Here are some scene shots.
![Screen Shot 2023-05-13 at 6 37 00 PM](https://github.com/JMRI/website/assets/17280992/0645bf76-d65f-4710-9fcb-d47080fef189)

![Screen Shot 2023-05-13 at 6 37 19 PM](https://github.com/JMRI/website/assets/17280992/389bd7e0-b1f7-4909-bd94-6d075bf9c958)

![Screen Shot 2023-05-13 at 6 37 33 PM](https://github.com/JMRI/website/assets/17280992/e5c33214-885c-448b-ad8a-3b57ca347f84)

**Comment by danielb987** [comment]
> The print CSS has issues with some content. Here are some scene shots.

Thanks.

> 5. Starting JmriFaceless

I suggest changing this to:

5. Starting JmriFaceless using any of these methods

I thought you ment that I should do all the steps, not one of them.

Also, I suggest that you add a note on where to find the rc.local file.
