### ISSUE TITLE
How to link issues with pull requests

### ISSUE THREAD

**Issue by jerryg2003** [JMRI/website#408]
Do I need a special permission to do this (here and in the JMRI repository)?  Will not let me click on anything to do this and no gear symbol.  Thanks.

**Comment by danielb987** [comment]
Is it this gear that you don't see? See the red arrow in the bottom right of the image.

![linked_pull_requests](https://user-images.githubusercontent.com/20255317/113575933-ef207880-961e-11eb-8218-887acd112e41.png)

**Comment by jerryg2003** [comment]
Yup.  Not there for me in either repository.

**Comment by bobjacobsen** [comment]
If you comment with the PR number or Issue number, it'll create a link.  (You can also do that across repositories, i..e from web site to JMRI or vice versa)
