### ISSUE TITLE
New program for Community Connections

### ISSUE THREAD

**Issue by HarlanSub** [JMRI/website#413]
Greetings,  I have written a program that formats switch lists and manifests created by JMRI.  While similar to Manifest Creator, my program is written in Java and thus avoids the need to have Excel.  It also runs on both PC & Mac.  I would appreciate it if the program could be listed on the Community Connections page on the JMRI website.   Dan Foltz has downloaded and tried the program already.  
Program Title:  Model Railroad Switch List and Manifest Formatter (MR SLAM Formatter)

Program website link  https://mrslamf.com/

Program description: Model Railroad Switch List and Manifest Formatter (MR SLAM Formatter) reads in a JMRI created manifest or switch list CSV file, formats the data according to the user’s settings, and then writes the manifest or switch list to a PDF file. The PDF may be printed directly from the program or opened for viewing with Adobe’s free program Acrobat Reader.   MR SLAM Formatter  offers numerous options to customize your manifests and switch lists.  MR SLAM Formatter runs under both Windows 10 and Mac OS X 10.15 and is available as a free download from the website.  

I'm new to GitHub so apologies if this is not the correct way to submit such a request.  If you have any questions, let me know.

Regards,

Tim Mann

**Comment by bobjacobsen** [comment]
Nice!

I propose to add this to the "[Applications that Connect](https://www.jmri.org/community/connections/CommunityConnectionsIndex.shtml)" page, and put an item at the top on the new items section on the [main JMRI page](https://jmri.org).  OK?

**Comment by HarlanSub** [comment]
That would be great Bob. Thank you

Tim Mann

**Comment by bobjacobsen** [comment]
Added via PR #414
