### ISSUE TITLE
Release note for 4.23.6 doesn't make draft status clear...

### ISSUE THREAD

**Issue by newHeiko** [JMRI/website#415]
...and it shows up in the sidebar, so I was just attempting to fix it, until I noticed there is no 4.23.6 release.

Shouldn't the draft status be clearer? Maybe like I did in PR https://github.com/silverailscolo/website/pull/15 ?

Heiko

**Comment by bobjacobsen** [comment]
I think this is just transient due to the new-web-form testing.  The release note on master has the line about "This is a draft release note only; the download links do not yet work"

**Comment by bobjacobsen** [comment]
Also, it should be under "next release" in the side bar. Is that not right?  If so, where?

**Comment by newHeiko** [comment]
Yes, Egbert merged my PR https://github.com/silverailscolo/website/pull/15 which solved this issue.

Since it's a different repo, it didn't get auto-closed.

Carry on, there's nothing to see here ;)

Heiko
