### ISSUE TITLE
Suggested fix for Acknowledgements page Sidebar links getting 404s

### ISSUE THREAD

**Issue by jerryg2003** [JMRI/website#432]
See JMRI Issue #9837.  help/en/Acknowledgements.shtml in the JMRI repository points to /Sidebar.shtml in the web repository.  /Sidebar.shtml in this repository has all the links set up with an initial "./"

If I remove the "." then the Acknowledgements.shtml links will work.  But are there any other (negative) ramifications of this change?

Thanks.

**Comment by danielb987** [comment]
@silverailscolo @dsand47 
I mention you to notify you about this issue in case you haven't seen it already.

**Comment by dsand47** [comment]
How about using the html sidebar for acknowledgments.
```
    <!--#include virtual="html/Sidebar.shtml" --> <!-- might be improved to show an Alphabet sidebar + some nav? -->
```

Another approach would be to create a sidebar at help/en for use by acknowledgments.

**Comment by jerryg2003** [comment]
I've been trying for a couple of years to reduce the number of different sidebars unless really necessary, so I'll just change to use the html/Sidebar.shtml.  Thanks.

**Comment by jerryg2003** [comment]
Suggestions have been made in the JMRI/JMRI pull request #9960 about improving navigation for the acknowledgements page.  Given that we haven’t yet agreed on whether or what to implement, I have submitted PR #433 to at least users won’t get broken links on the sidebar from the acknowledgements page.

**Comment by jerryg2003** [comment]
Resolved by putting new Sidebar into html directory in JMRI/JMRI repository.
