### ISSUE TITLE
Change java requirement statement

### ISSUE THREAD

**Issue by PUlvestad** [JMRI/website#441]
https://www.jmri.org/help/en/html/setup/
Current:
JMRI® requires that Java be installed:

    Version 2.12 can run on any computer system that will run Java 1.5 through Java 8 (also known as Java 1.8).
    Version 2.14.1 requires Java 1.5 (or Java 1.6 to support for drag & drop) through Java 8.
    Version 3.10.1 requires Java 1.7 through Java 8.
    Version 4.2 requires Java 8.

Version 4.2 requires Java 8 is giving the impression only 8 can be used
Change to --Version 4.2 requires Java 8 through Java 11.--

For reference:
https://groups.io/g/jmriusers/message/193999

**Comment by bobjacobsen** [comment]
Would it make sense to say "Version 4.2 and later requires Java 8 through 11. If your machine can run it, we recommend Java 11."?

I think we should _not_ change the recommendations for 2.12, 2.14.1 and 3.10.1, instead leaving them to say "through Java 8".  We haven't tested those with Java 11.

**Comment by danielb987** [comment]
I agree.

**Comment by PUlvestad** [comment]
Yes, that is fine with me.

**Comment by bobjacobsen** [comment]
See PR JMRI/JMRI#10097

**Comment by danielb987** [comment]
Closing this since it's resolved by https://github.com/JMRI/JMRI/pull/10097.
