### ISSUE TITLE
Schema examples fall off the right edge of page

### ISSUE THREAD

**Issue by devel-bobm** [JMRI/website#522]
The text for the `https://www.jmri.org/help/en/html/doc/Technical/XmlSchemaExamples.shtml` page falls off the right edge of the page.

**Comment by dsand47** [comment]
This can be fixed by removing the code tags or adding class="block" to the code tags and removing the pre tags.

**Comment by devel-bobm** [comment]
And, the page has no "vertical scrollbar".

**Comment by danielb987** [comment]
Is this issue fixed by https://github.com/JMRI/JMRI/pull/12286 ?

**Comment by bobjacobsen** [comment]
It is for Safari and Chrome on Mac.  Don't know what browser @devel-bobm was using.

**Comment by devel-bobm** [comment]
@bobjacobsen, I use Firefox on Windows 11.  But I do not currently have easy access to my development environment, tho.

**Comment by bobjacobsen** [comment]
Could you try accessing the page on the web?

[https://www.jmri.org/help/en/html/doc/Technical/XmlSchemaExamples.shtml](https://www.jmri.org/help/en/html/doc/Technical/XmlSchemaExamples.shtml)

**Comment by devel-bobm** [comment]
@bobjacobsen, MUCH better!
![Image1](https://github.com/JMRI/website/assets/13856693/300d4c15-caeb-413c-a5a2-21ebec212263)

Thanks for addressing this!
