### ISSUE TITLE
DCC Pocket Analyzer

### ISSUE THREAD

**Issue by djcalcutt** [JMRI/website#537]
Not sure if is the place to  request or post recommendations. Just learning so take it easy on me.

In the NCE DCC pocket analyzer, can I get the time-date  stamp to be placed first in the log (displayed window) then a space, then the command? 

Can the options I last clicked on (the bullet options) be remembered?

Can the file name lasted used  be remembered and restored when opening up the window? I use this a lot in sourcing problems with DCC.

Thank you for the great work. I look forward to contributing the the project. Trying to learn Java and Javascript.

Darrin.

**Comment by KenC57** [comment]
Darrin,

Which version of the analyzer and JMRI are you using? My memory has
the timestamp first, if enabled as that is a normal part of the
logging window.

-Ken Cameron, Member JMRI Dev Team
www.jmri.org
www.fingerlakeslivesteamers.org
www.cnymod.com

**Comment by mstevetodd** [comment]
Darrin, I recommend you post a screenshot of the window showing the problem you're trying to describe. Screenshots save a lot of time.
--SteveT

**Comment by djcalcutt** [comment]
My JMRI OS 5.6 and jave is just updatedDarrin J. CalcuttSent from my iPhoneOn Mar 18, 2024, at 18:47, Ken Cameron ***@***.***> wrote:﻿
Darrin,

Which version of the analyzer and JMRI are you using? My memory has
the timestamp first, if enabled as that is a normal part of the
logging window.

-Ken Cameron, Member JMRI Dev Team
www.jmri.org
www.fingerlakeslivesteamers.org
www.cnymod.com

**Comment by KenC57** [comment]
I would suggest upgrading to 5.7.5 as I did a big rework of the
monitor support for including the new one NCE released. The work was
done via 5.7.1 and 5.7.2 but there might have been a minor fix or two
since then.

**Comment by djcalcutt** [comment]
![image](https://github.com/JMRI/website/assets/61532140/af44d9f7-ae9d-4424-a433-9591f0ca3120)

Thank you. 

Also i just want to say thank you. 

Your JMRI has allowed me to continue on with my venture of operating trains over the internet. 

I look forward to adding rtsp video feeds from my camera into a GUI to replace the throttle.

**Comment by djcalcutt** [comment]
You can close this. 

If it persists, I'll  chime back in.
